version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db_maxi
      MYSQL_USER: maxiuser
      MYSQL_ROOT_PASSWORD: qwerty123
    ports:
      - 3306:3306

  server:
    build: .
    container_name: alpine
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db